apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-auth
  template:
    metadata:
      labels:
        app: api-auth
    spec:
      containers:
        - name: api-auth
          image: csgn/clido-auth
          env:
            - name: JWT_KEY
              valueFrom: 
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: api-auth-srv
spec:
  selector:
    app: api-auth
  ports:
    - name: api-auth
      protocol: TCP
      port: 4000
      targetPort: 4000